// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARILuENzjK6pO36MlBTZY8GYpMMDgHgSU',
    appId: '1:102452154420:web:702155a79ef7deaf803a61',
    messagingSenderId: '102452154420',
    projectId: 'print-39805',
    authDomain: 'print-39805.firebaseapp.com',
    storageBucket: 'print-39805.appspot.com',
    measurementId: 'G-FT4C8R684D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEMG_i_CAznq2aOniMbRbmLLOmSyi_kb8',
    appId: '1:102452154420:android:23e61ab41ac131b6803a61',
    messagingSenderId: '102452154420',
    projectId: 'print-39805',
    storageBucket: 'print-39805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgjfoxSMGCXLPKceLi_KcIMjCPhF7GZsA',
    appId: '1:102452154420:ios:7342f9129e872b7f803a61',
    messagingSenderId: '102452154420',
    projectId: 'print-39805',
    storageBucket: 'print-39805.appspot.com',
    androidClientId: '102452154420-u01js9a1t4sdgciklq85mvs6p8kdkn0e.apps.googleusercontent.com',
    iosClientId: '102452154420-rarm3j4dvpo614ravscmrg73kgohhqfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.printsecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgjfoxSMGCXLPKceLi_KcIMjCPhF7GZsA',
    appId: '1:102452154420:ios:7342f9129e872b7f803a61',
    messagingSenderId: '102452154420',
    projectId: 'print-39805',
    storageBucket: 'print-39805.appspot.com',
    androidClientId: '102452154420-u01js9a1t4sdgciklq85mvs6p8kdkn0e.apps.googleusercontent.com',
    iosClientId: '102452154420-rarm3j4dvpo614ravscmrg73kgohhqfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.printsecure',
  );
}
